package:
  name: hyp2f1a1
  version: 0.1

source:
  git_url: https://github.com/alicedb2/hyp2f1a1.git

build:
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - {{ compiler('c') }}
    - cython
    - scipy

  run:
    - python

tests:
  imports:
    - hyp2f1a1
